# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OldObjcExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OldObjcExample
  pod 'Sentry', :path => '../../'
  pod 'KSCrash', :git => 'https://github.com/kstenerud/KSCrash', :tag => '1.15.2', :subspecs => ['Installations', 'Recording']

end
